function ProjectDetail({ project, role, onNotify, onEnquiry }: { project: Project; role: Role; onNotify: (message: string) => void; onEnquiry?: () => void }) { return <><BaseProjectDetail project={project} role={role} onNotify={onNotify} onEnquiry={onEnquiry} /><section className="crm-detail-grid"><section className="panel"><Head eyebrow="Project record" title="Financial snapshot" /><div className="detail-financials"><span><small>Project value</small><strong>{project.value}</strong></span><span><small>Estimated cost</small><strong>{project.cost}</strong></span><span><small>Gross margin</small><strong>{Math.round((1 - Number(project.cost.replace('$', '').replace('m', '')) / Number(project.value.replace('$', '').replace('m', ''))) * 100)}%</strong></span></div></section><section className="panel"><Head eyebrow="Project record" title="Record details" /><div className="record-details"><span><small>Status</small><strong>{project.status}</strong></span><span><small>Category</small><strong>{project.category}</strong></span><span><small>Documents</small><strong>{project.documents} files</strong></span></div></section></section></> }
import { useEffect, useState } from 'react'
import './App.css'

type Role = 'public' | 'staff' | 'investor'
type View = 'overview' | 'projects' | 'investors' | 'exit'
type Project = { name: string; location: string; category: string; status: 'New' | 'In development' | 'Completed'; progress: number; value: string; cost: string; documents: number; color: string; image: string; description: string }

const images = {
  residential: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80',
  commercial: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=80',
  rural: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80',
  dubai: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=900&q=80',
  india: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=900&q=80',
  other: 'https://images.unsplash.com/photo-1473445361085-b9a07f55608b?auto=format&fit=crop&w=900&q=80',
}

const projects: Project[] = [
  { name: 'Willowbank Estate', location: 'Adelaide, SA', category: 'Residential land', status: 'In development', progress: 42, value: '$18.4m', cost: '$11.2m', documents: 6, color: 'sage', image: images.residential, description: 'A considered residential community shaped by land, landscape and a clear delivery plan.' },
  { name: 'North Harbour Trade', location: 'Newcastle, NSW', category: 'Commercial land', status: 'New', progress: 24, value: '$11.8m', cost: '$7.4m', documents: 4, color: 'ochre', image: images.commercial, description: 'A connected trade precinct positioned for the next generation of local enterprise.' },
  { name: 'Mallee Fields', location: 'Murray Bridge, SA', category: 'Farming land', status: 'In development', progress: 68, value: '$9.2m', cost: '$6.1m', documents: 8, color: 'blue', image: images.rural, description: 'Productive rural land with a long-term view across agriculture, water and stewardship.' },
  { name: 'Palm Jumeirah Residences', location: 'Dubai, UAE', category: 'Dubai property', status: 'In development', progress: 55, value: '$24.6m', cost: '$17.8m', documents: 7, color: 'ochre', image: images.dubai, description: 'A premium Dubai residential opportunity with an established delivery partner.' },
  { name: 'Bandra Heights', location: 'Mumbai, India', category: 'Property - India', status: 'New', progress: 18, value: '$8.7m', cost: '$5.9m', documents: 3, color: 'blue', image: images.india, description: 'A carefully selected urban property opportunity in one of Mumbai\'s most connected districts.' },
  { name: 'Riverstone Gardens', location: 'Sydney, NSW', category: 'Residential land', status: 'Completed', progress: 100, value: '$15.1m', cost: '$9.8m', documents: 12, color: 'sage', image: images.residential, description: 'A completed community delivering settled homes and strong investor outcomes.' },
  { name: 'Cedar Grove', location: 'Geelong, VIC', category: 'Residential land', status: 'In development', progress: 61, value: '$13.9m', cost: '$8.9m', documents: 6, color: 'sage', image: images.residential, description: 'A growing residential release with a clear path from planning to settlement.' },
  { name: 'Marina Logistics Park', location: 'Port Adelaide, SA', category: 'Commercial land', status: 'In development', progress: 47, value: '$21.5m', cost: '$14.4m', documents: 9, color: 'ochre', image: images.commercial, description: 'Strategic commercial land close to freight, port and major transport connections.' },
  { name: 'Eastern Creek Enterprise', location: 'Western Sydney, NSW', category: 'Commercial land', status: 'New', progress: 12, value: '$19.2m', cost: '$12.8m', documents: 3, color: 'ochre', image: images.commercial, description: 'An early-stage enterprise precinct with flexible commercial potential.' },
  { name: 'Golden Plains', location: 'Ballarat, VIC', category: 'Farming land', status: 'Completed', progress: 100, value: '$7.8m', cost: '$5.2m', documents: 11, color: 'blue', image: images.rural, description: 'A productive rural holding completed with a focus on sustainable land use.' },
  { name: 'Barossa Orchard', location: 'Barossa Valley, SA', category: 'Farming land', status: 'In development', progress: 73, value: '$10.6m', cost: '$7.3m', documents: 8, color: 'blue', image: images.rural, description: 'A high-quality agricultural holding in a globally recognised food and wine region.' },
  { name: 'Al Ain Agro Estate', location: 'Al Ain, UAE', category: 'Dubai property', status: 'New', progress: 9, value: '$6.4m', cost: '$4.2m', documents: 2, color: 'ochre', image: images.dubai, description: 'A land-backed agricultural property opportunity in the UAE.' },
  { name: 'Creekside Villas', location: 'Dubai, UAE', category: 'Dubai property', status: 'Completed', progress: 100, value: '$16.7m', cost: '$11.5m', documents: 10, color: 'ochre', image: images.dubai, description: 'A completed villa project with final investor distributions underway.' },
  { name: 'Pune Growth Corridor', location: 'Pune, India', category: 'Property - India', status: 'In development', progress: 36, value: '$12.3m', cost: '$8.1m', documents: 5, color: 'blue', image: images.india, description: 'A growth-corridor property positioned for long-term urban expansion.' },
  { name: 'Bengaluru Tech Quarter', location: 'Bengaluru, India', category: 'Property - India', status: 'Completed', progress: 100, value: '$14.2m', cost: '$9.7m', documents: 13, color: 'blue', image: images.india, description: 'A completed mixed-use property near Bengaluru\'s technology precinct.' },
  { name: 'Harbour View Apartments', location: 'Wollongong, NSW', category: 'Residential land', status: 'New', progress: 15, value: '$17.6m', cost: '$11.9m', documents: 3, color: 'sage', image: images.residential, description: 'A coastal residential site with strong amenity and transport connections.' },
  { name: 'Summit Living', location: 'Canberra, ACT', category: 'Residential land', status: 'In development', progress: 79, value: '$12.7m', cost: '$8.5m', documents: 9, color: 'sage', image: images.residential, description: 'A near-complete residential project with settlement planning underway.' },
  { name: 'Airport Business Park', location: 'Brisbane, QLD', category: 'Commercial land', status: 'In development', progress: 51, value: '$23.1m', cost: '$15.6m', documents: 7, color: 'ochre', image: images.commercial, description: 'A commercial land holding designed for logistics and light industrial demand.' },
  { name: 'Southlink Warehousing', location: 'Melbourne, VIC', category: 'Commercial land', status: 'Completed', progress: 100, value: '$20.4m', cost: '$13.7m', documents: 14, color: 'ochre', image: images.commercial, description: 'A completed warehousing precinct with leases and settlements finalised.' },
  { name: 'Riverina Harvest', location: 'Wagga Wagga, NSW', category: 'Farming land', status: 'New', progress: 11, value: '$8.9m', cost: '$5.8m', documents: 3, color: 'blue', image: images.rural, description: 'A diversified farming opportunity with strong water and access fundamentals.' },
  { name: 'Clare Valley Land', location: 'Clare Valley, SA', category: 'Farming land', status: 'In development', progress: 64, value: '$7.1m', cost: '$4.7m', documents: 6, color: 'blue', image: images.rural, description: 'A managed rural property with a clear pathway toward productive use.' },
  { name: 'AEG International Fund I', location: 'Multiple locations', category: 'Other', status: 'In development', progress: 48, value: '$26.8m', cost: '$18.3m', documents: 8, color: 'sage', image: images.other, description: 'A diversified property allocation across selected AEG markets.' },
  { name: 'Lake Macquarie Renewal', location: 'Lake Macquarie, NSW', category: 'Other', status: 'New', progress: 7, value: '$10.5m', cost: '$6.9m', documents: 2, color: 'sage', image: images.other, description: 'An early-stage renewal opportunity with a strong local regeneration thesis.' },
  { name: 'Coorong Eco Retreat', location: 'Coorong, SA', category: 'Other', status: 'Completed', progress: 100, value: '$5.6m', cost: '$3.8m', documents: 9, color: 'blue', image: images.other, description: 'A completed destination property with operations transitioned to its owner.' },
  { name: 'Northern Beaches Sites', location: 'Sydney, NSW', category: 'Other', status: 'In development', progress: 33, value: '$9.8m', cost: '$6.4m', documents: 5, color: 'sage', image: images.other, description: 'A small-site acquisition program focused on high-quality infill locations.' },
]
const milestoneNames = ['Land settlement', 'Feasibility sign-off', 'DA approval', 'Construction certificate', 'Civil works complete', 'Subdivision registration', 'Lots sold & settled']

function App() {
  const [role, setRole] = useState<Role>('staff')
  const [view, setView] = useState<View>('overview')
  const [project, setProject] = useState(projects[0])
  const [projectDetailOpen, setProjectDetailOpen] = useState(false)
  const [assistant, setAssistant] = useState(false)
  const [enquiry, setEnquiry] = useState(false)
  const [newProjectOpen, setNewProjectOpen] = useState(false)
  const [notice, setNotice] = useState('')
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2400) }
  const openProject = (nextProject = projects[0]) => { setProject(nextProject); setProjectDetailOpen(true); setView('projects') }
  const publicSite = role === 'public'
  void ProjectDetail
  void ProjectRecord
  useEffect(() => {
    window.scrollTo({ top: 0, left: 0, behavior: 'auto' })
  }, [role, view, projectDetailOpen])
  return <div className="app-shell">
    <header className="topbar"><button className="brand" onClick={() => { setRole('public'); setView('overview') }}><span className="brand-mark">AEG</span><span><strong>Alliance Estate</strong><small>Group</small></span></button><div className="role-switcher">{(['public', 'staff', 'investor'] as Role[]).map((item) => <button key={item} className={role === item ? 'active' : ''} onClick={() => { setRole(item); setView('overview') }}>{item}</button>)}</div><button className="avatar" onClick={() => notify('Profile menu opened')}>JD</button></header>
    <div className="app-body"><aside className="sidebar"><p className="workspace-label">{publicSite ? 'PUBLIC SITE' : role === 'staff' ? 'AEG WORKSPACE' : 'INVESTOR PORTAL'}</p><nav><Nav active={view === 'overview'} label="Overview" icon="⌂" onClick={() => { setProjectDetailOpen(false); setView('overview') }} />{!publicSite && <Nav active={view === 'projects'} label="Projects" icon="▦" count="25" onClick={() => { setProjectDetailOpen(false); setView('projects') }} />}{!publicSite && <Nav active={view === 'investors'} label={role === 'staff' ? 'Investors' : 'Messages'} icon="◎" count="4" onClick={() => setView('investors')} />}{!publicSite && <Nav active={view === 'exit'} label={role === 'staff' ? 'Unit trust & exits' : 'My distributions'} icon="↗" onClick={() => setView('exit')} />}</nav><small className="sidebar-foot">● All systems operational</small></aside>
      <main className="content">{publicSite && !projectDetailOpen ? <PublicView onProject={openProject} onAssistant={() => setAssistant(true)} /> : publicSite ? <><button className="back-link" onClick={() => { setProjectDetailOpen(false); setView('overview') }}>← Back to available projects</button><BaseProjectDetail project={project} role={role} onNotify={notify} onEnquiry={() => setEnquiry(true)} /></> : <>{view === 'projects' && !projectDetailOpen ? <ProjectsIndex onProject={openProject} /> : <><div className="page-heading"><div><p className="eyebrow">{role === 'staff' ? 'Tuesday, 10 September 2026' : 'Welcome back, Jordan'}</p><h1>{view === 'overview' ? role === 'staff' ? 'Good morning, Jordan' : 'Your portfolio' : view === 'projects' ? project.name : view === 'investors' ? 'Investor relations' : 'Unit trust & exits'}</h1></div><button className="primary" onClick={() => role === 'staff' ? setNewProjectOpen(true) : notify('Enquiry form opened')}>＋ {role === 'staff' ? 'New project' : 'Ask AEG a question'}</button></div>{view === 'overview' && <Dashboard role={role} onProject={openProject} />}{view === 'projects' && <><button className="back-link" onClick={() => setProjectDetailOpen(false)}>← Back to all projects</button><BaseProjectDetail project={project} role={role} onNotify={notify} /></>}{view === 'investors' && <Messages role={role} />}{view === 'exit' && <Exit role={role} onNotify={notify} />}</>}</>}</main></div>
    {assistant && <Assistant onClose={() => setAssistant(false)} onNotify={notify} />}{enquiry && <Enquiry project={project} onClose={() => setEnquiry(false)} onNotify={notify} />}{newProjectOpen && <NewProjectForm onClose={() => setNewProjectOpen(false)} onNotify={notify} />}{notice && <div className="toast">{notice}</div>}
  </div>
}

function Nav({ active, label, icon, count, onClick }: { active: boolean; label: string; icon: string; count?: string; onClick: () => void }) { return <button className={active ? 'selected' : ''} onClick={onClick}><span>{icon}</span>{label}{count && <b>{count}</b>}</button> }
function Dashboard({ role, onProject }: { role: Role; onProject: (project?: Project) => void }) { return <><div className="metric-grid"><Metric label={role === 'staff' ? 'Active projects' : 'Invested projects'} value={role === 'staff' ? '25' : '3'} note="Across 2 states" /><Metric label="Portfolio value" value="$86.4m" note="Updated 2 hours ago" /><Metric label={role === 'staff' ? 'Open risks' : 'Next update'} value={role === 'staff' ? '08' : '18 Sep'} note={role === 'staff' ? '3 high priority' : 'Willowbank Estate'} tone="warm" /><Metric label={role === 'staff' ? 'Investor questions' : 'Documents ready'} value={role === 'staff' ? '04' : '07'} note="For your review" tone="green" /></div><div className="feature-grid"><section className="panel project-feature"><Head eyebrow="Project spotlight" title="Willowbank Estate" badge="In progress" /><div className="feature-image sage-image">WILLOWBANK<br /><small>ESTATE</small></div><div className="project-meta"><span><strong>Adelaide, SA</strong><small>Residential land</small></span><span><strong>42%</strong><small>Overall progress</small></span><span><strong>Sep 2027</strong><small>Estimated completion</small></span></div><Progress value={42} /><button className="text-link" onClick={() => onProject()}>View project details →</button></section><section className="panel activity"><Head eyebrow="Recent activity" title="Keep things moving" /><Activity title="DA approval milestone updated" detail="Willowbank Estate · 2h ago" icon="↗" /><Activity title="Investor update published" detail="Mallee Fields · Yesterday" icon="✦" /><Activity title="New investor question" detail="Sarah Chen · Yesterday" icon="?" /><Activity title="Feasibility report uploaded" detail="North Harbour · 2d ago" icon="▤" /></section></div><section className="panel table-panel"><Head eyebrow="Portfolio" title={role === 'staff' ? 'All projects' : 'Your projects'} /><div className="project-list">{projects.map((item) => <button className="project-row" key={item.name} onClick={() => onProject(item)}><span className={`project-thumb ${item.color}`} /><span><strong>{item.name}</strong><small>{item.location}</small></span><span className="row-category">{item.category}</span><span className="row-progress"><small>{item.progress}% complete</small><Progress value={item.progress} /></span><span className="row-value">{item.value}</span><span>→</span></button>)}</div></section></> }
function ProjectsIndex({ onProject }: { onProject: (project: Project) => void }) {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('All categories')
  const [status, setStatus] = useState('All statuses')
  const categories = ['All categories', 'Residential land', 'Commercial land', 'Farming land', 'Dubai property', 'Property - India', 'Other']
  const statuses = ['All statuses', 'New', 'In development', 'Completed']
  const filtered = projects.filter((item) => (category === 'All categories' || item.category === category) && (status === 'All statuses' || item.status === status) && `${item.name} ${item.location} ${item.category}`.toLowerCase().includes(query.toLowerCase()))
  const totalValue = filtered.reduce((sum, item) => sum + Number(item.value.replace('$', '').replace('m', '')), 0).toFixed(1)
  return <div className="projects-index">
    <div className="page-heading"><div><p className="eyebrow">AEG PROJECT CRM</p><h1>All projects</h1><p className="index-intro">Track every AEG project, from first feasibility through to settlement.</p></div><button className="primary" onClick={() => onProject(projects[0])}>＋ Open project record</button></div>
    <div className="crm-summary"><Metric label="Visible projects" value={`${filtered.length}`} note="of 25 total records" /><Metric label="Portfolio value" value={`$${totalValue}m`} note="Filtered portfolio total" /><Metric label="In development" value={`${filtered.filter((item) => item.status === 'In development').length}`} note="Active delivery records" /><Metric label="Documents" value={`${filtered.reduce((sum, item) => sum + item.documents, 0)}`} note="Available in library" tone="green" /></div>
    <section className="panel projects-index-panel"><div className="crm-toolbar"><label className="search-field"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, location or category" /></label><select value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)}>{statuses.map((item) => <option key={item}>{item}</option>)}</select></div><div className="crm-table"><div className="crm-table-head"><span>Project</span><span>Category</span><span>Status</span><span>Progress</span><span>Value / cost</span><span>Docs</span></div>{filtered.map((item) => <button className="crm-row" key={item.name} onClick={() => onProject(item)}><span className="crm-project"><span className={`project-thumb ${item.color}`} /><span><strong>{item.name}</strong><small>{item.location}</small></span></span><span>{item.category}</span><span><i className={`status-dot ${item.status.toLowerCase().replace(' ', '-')}`} />{item.status}</span><span><small>{item.progress}% complete</small><Progress value={item.progress} /></span><span><strong>{item.value}</strong><small>Cost {item.cost}</small></span><span>{item.documents} files <b>→</b></span></button>)}</div>{filtered.length === 0 && <div className="empty-state">No projects match these filters.</div>}</section>
  </div>
}

function PublicView({ onProject, onAssistant }: { onProject: (project: Project) => void; onAssistant: () => void }) {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('All projects')
  const [saved, setSaved] = useState<string[]>([])
  const categories = ['All projects', 'Residential land', 'Commercial land', 'Farming land', 'Dubai property', 'Property - India', 'Other']
  const filteredProjects = projects.filter((item) => (category === 'All projects' || item.category === category) && `${item.name} ${item.location}`.toLowerCase().includes(query.toLowerCase()))
  return <><section className="listings-header"><div><p className="eyebrow">AEG PROPERTY PORTFOLIO</p><h1>Available<br /><em>opportunities.</em></h1><p>Explore current projects across Australia and beyond, with stage-wise updates from the teams delivering them.</p></div><div className="listing-count"><strong>{filteredProjects.length}</strong><span>shown<br />of 25 projects</span></div></section><section className="listing-toolbar"><div className="listing-filters">{categories.map((item) => <button key={item} className={category === item ? 'filter-active' : ''} onClick={() => setCategory(item)}>{item}</button>)}<button className={category === 'Saved' ? 'filter-active' : ''} onClick={() => setCategory('Saved')}>Saved ({saved.length})</button></div><div className="listing-actions"><label className="search-field"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search projects" /></label><button className="secondary" onClick={onAssistant}>✦ AEG Guide</button></div></section><section className="public-section listings-section"><div className="section-intro"><p className="eyebrow">CURRENT PROJECTS</p><h2>Places worth<br /><em>watching.</em></h2><p>Browse available opportunities and follow each project from feasibility through to settlement.</p></div><div className="public-cards">{(category === 'Saved' ? projects.filter((item) => saved.includes(item.name)) : filteredProjects).map((item) => <article className="public-card" key={item.name}><button className="public-card-open" onClick={() => onProject(item)}><div className="public-image" style={{ backgroundImage: `url(${item.image})` }}><span>{item.name.split(' ')[0]}</span><small>{item.progress}% complete</small></div><span className="eyebrow">{item.category}</span><h3>{item.name}</h3><p>{item.location} <span>View project →</span></p></button><button className={`save-button ${saved.includes(item.name) ? 'saved' : ''}`} aria-label={`Save ${item.name}`} onClick={() => setSaved((current) => current.includes(item.name) ? current.filter((name) => name !== item.name) : [...current, item.name])}>{saved.includes(item.name) ? '♥ Saved' : '♡ Save project'}</button></article>)}</div>{filteredProjects.length === 0 && <div className="empty-state"><strong>No projects match that search.</strong><button className="text-link" onClick={() => { setQuery(''); setCategory('All projects') }}>Clear filters</button></div>}</section><section className="story-strip"><span className="eyebrow">OUR STORY</span><h2>25 projects.<br />One considered approach.</h2><button className="text-link light-link">Meet AEG →</button></section></> }
function BaseProjectDetail({ project, role, onNotify, onEnquiry }: { project: Project; role: Role; onNotify: (message: string) => void; onEnquiry?: () => void }) { return <div className="view-stack"><div className="project-hero"><div className="project-hero-image" style={{ backgroundImage: `url(${project.image})` }} /><div><span className="eyebrow">{project.category} · {project.location}</span><h2>{project.name}</h2><p>{project.description}</p><div className="project-stat-row"><span><strong>{project.value}</strong><small>Gross project value</small></span><span><strong>{project.progress}%</strong><small>Project progress</small></span><span><strong>Sep 2027</strong><small>Target completion</small></span></div>{onEnquiry && <button className="primary enquiry-button" onClick={onEnquiry}>Enquire about this project →</button>}</div></div><div className="detail-tabs"><button className="active">Overview</button><button onClick={() => onNotify('Document tab opened')}>Documents <b>6</b></button><button onClick={() => onNotify('Update feed opened')}>Updates <b>3</b></button><button onClick={() => onNotify('Risk register opened')}>Risks <b>2</b></button></div><div className="detail-grid"><section className="panel"><Head eyebrow="Delivery timeline" title="Project milestones" /><div className="milestone-list">{milestoneNames.map((name, index) => <div className={`milestone ${index < 2 ? 'done' : index === 2 ? 'current' : ''}`} key={name}><span className="milestone-node">{index < 2 ? '✓' : `M${index + 1}`}</span><div><strong>{name}</strong><small>{index < 2 ? 'Complete · 12 Mar 2026' : index === 2 ? 'In progress · Target 30 Oct 2026' : 'Upcoming · Target 2027'}</small></div></div>)}</div></section><section className="panel update-panel"><Head eyebrow="Latest update" title="Moving through approvals" badge="18 Sep 2026" /><p>Our planning team has responded to the latest council RFI. Engineering documentation is now being finalised for the next submission.</p><button className="secondary" onClick={() => onNotify('Update marked as read')}>Read full update</button></section></div><section className="panel"><Head eyebrow="Documents" title="Project library" /><div className="document-grid"><Document name="Feasibility report" detail="PDF · 2.4 MB" /><Document name="Investor update · Sep 2026" detail="PDF · 840 KB" /><Document name="Planning approval register" detail="XLSX · 128 KB" /></div></section>{role === 'staff' && <section className="panel risk-panel"><Head eyebrow="Internal only" title="Risk register" /><Risk title="DA response timeframe" level="High" /><Risk title="Construction cost movement" level="Med" /></section>}</div> }
function ProjectRecord({ project, role, onNotify }: { project: Project; role: Role; onNotify: (message: string) => void }) { return <><BaseProjectDetail project={project} role={role} onNotify={onNotify} /><section className="crm-detail-grid"><section className="panel"><Head eyebrow="Project record" title="Financial snapshot" /><div className="detail-financials"><span><small>Project value</small><strong>{project.value}</strong></span><span><small>Estimated cost</small><strong>{project.cost}</strong></span><span><small>Gross margin</small><strong>{project.value === project.cost ? '0%' : `${Math.round((1 - Number(project.cost.replace('$', '').replace('m', '')) / Number(project.value.replace('$', '').replace('m', ''))) * 100)}%`}</strong></span></div></section><section className="panel"><Head eyebrow="Project record" title="Record details" /><div className="record-details"><span><small>Status</small><strong>{project.status}</strong></span><span><small>Category</small><strong>{project.category}</strong></span><span><small>Documents</small><strong>{project.documents} files</strong></span></div></section></section></> }
function Messages({ role }: { role: Role }) { return <section className="panel message-panel"><Head eyebrow={role === 'staff' ? 'Investor communication' : 'Your inbox'} title={role === 'staff' ? 'Questions needing a reply' : 'Updates from AEG'} /><Message title="Question about Willowbank Estate" text="Could you share more detail on the expected settlement timing?" status="Open" /><Message title="September portfolio update" text="Three projects have moved forward this month." status="Published" /><Message title="Mallee Fields milestone" text="Civil works are now 68% complete." status="Read" /></section> }
function Exit({ role, onNotify }: { role: Role; onNotify: (message: string) => void }) { return <section className="panel exit-panel"><Head eyebrow={role === 'staff' ? 'Investor unit trust management' : 'Your investment journey'} title={role === 'staff' ? 'Exit process tracker' : 'Distributions & exits'} /><div className="exit-summary"><div><small>Next expected distribution</small><strong>{role === 'staff' ? '$2.8m' : '$48,600'}</strong><span>Willowbank Estate · Q2 2027</span></div><div><small>Sign-offs complete</small><strong>{role === 'staff' ? '18 / 24' : '2 / 3'}</strong><span>Across active exit processes</span></div></div><div className="exit-steps"><span className="complete">1. Exit notice</span><span className="complete">2. Valuation</span><span className="current">3. Distribution</span><span>4. Sign-off</span></div><button className="secondary" onClick={() => onNotify('Exit tracker exported')}>Export report</button></section> }
function Head({ eyebrow, title, badge }: { eyebrow: string; title: string; badge?: string }) { return <div className="panel-head"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{badge && <span className="badge progress">{badge}</span>}</div> }
function Metric({ label, value, note, tone = '' }: { label: string; value: string; note: string; tone?: string }) { return <div className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></div> }
function Progress({ value }: { value: number }) { return <span className="progress-bar"><i style={{ width: `${value}%` }} /></span> }
function Activity({ title, detail, icon }: { title: string; detail: string; icon: string }) { return <div className="activity-row"><span className="activity-icon">{icon}</span><span><strong>{title}</strong><small>{detail}</small></span></div> }
function Document({ name, detail }: { name: string; detail: string }) { return <button className="document-row"><span>▤</span><span><strong>{name}</strong><small>{detail}</small></span><span>↓</span></button> }
function Risk({ title, level }: { title: string; level: string }) { return <div className="risk-row"><span className="risk-level">{level}</span><span><strong>{title}</strong><small>Approvals & regulatory · Owner: Jordan Davis</small></span><small className="risk-status">Monitoring</small></div> }
function Message({ title, text, status }: { title: string; text: string; status: string }) { return <button className="message-item"><span className="avatar">AE</span><span><strong>{title}</strong><small>{text}</small><small>AEG Investor Relations · Yesterday</small></span><span className="badge progress">{status}</span></button> }
function Assistant({ onClose, onNotify }: { onClose: () => void; onNotify: (message: string) => void }) { return <div className="modal-backdrop" onClick={onClose}><div className="assistant-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><span className="assistant-spark">✦</span><p className="eyebrow">AEG GUIDE</p><h2>Let’s find a place to start.</h2><p>Tell us what kind of opportunity you’re exploring.</p>{['Residential opportunities', 'Commercial opportunities', 'I’m still exploring'].map((item) => <button className="assistant-option" key={item} onClick={() => { onNotify(`Showing ${item.toLowerCase()}`); onClose() }}>{item} <span>→</span></button>)}</div></div> }
function Enquiry({ project, onClose, onNotify }: { project: Project; onClose: () => void; onNotify: (message: string) => void }) { const [submitted, setSubmitted] = useState(false); return <div className="modal-backdrop" onClick={onClose}><div className="assistant-modal enquiry-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button>{submitted ? <><span className="assistant-spark">✓</span><p className="eyebrow">MESSAGE RECEIVED</p><h2>We’ll be in touch.</h2><p>Your enquiry about {project.name} has been sent to the AEG team.</p><button className="primary" onClick={onClose}>Done</button></> : <><p className="eyebrow">PROJECT ENQUIRY</p><h2>Ask about {project.name}</h2><p>Leave your details and the AEG team will follow up with the latest project information.</p><form className="enquiry-form" onSubmit={(event) => { event.preventDefault(); setSubmitted(true); onNotify('Enquiry sent to AEG') }}><label>Name<input required placeholder="Your name" /></label><label>Email<input required type="email" placeholder="you@example.com" /></label><label>What would you like to know?<textarea required rows={3} placeholder="Tell us what you are looking for" /></label><button className="primary" type="submit">Send enquiry →</button></form></>}</div></div> }
function NewProjectForm({ onClose, onNotify }: { onClose: () => void; onNotify: (message: string) => void }) { const [submitted, setSubmitted] = useState(false); return <div className="modal-backdrop" onClick={onClose}><div className="assistant-modal new-project-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button>{submitted ? <><span className="assistant-spark">✓</span><p className="eyebrow">PROJECT CREATED</p><h2>Project added to CRM.</h2><p>The new project record is ready for feasibility, milestones, documents and investor updates.</p><button className="primary" onClick={onClose}>Done</button></> : <><p className="eyebrow">NEW PROJECT RECORD</p><h2>Add a project</h2><p>Start a new AEG project record. You can complete feasibility, milestones and documents after creation.</p><form className="enquiry-form new-project-form" onSubmit={(event) => { event.preventDefault(); setSubmitted(true); onNotify('New project added to CRM') }}><label>Project name<input required name="name" placeholder="e.g. Willowbank Estate" /></label><div className="form-row"><label>Category<select required name="category" defaultValue=""><option value="" disabled>Select category</option><option>Residential land</option><option>Commercial land</option><option>Farming land</option><option>Dubai property</option><option>Property - India</option><option>Other</option></select></label><label>Status<select required name="status" defaultValue="New"><option>New</option><option>In development</option><option>Completed</option></select></label></div><div className="form-row"><label>Location<input required name="location" placeholder="City, state or country" /></label><label>Project value<input required name="value" placeholder="$0.0m" /></label></div><label>Estimated cost<input required name="cost" placeholder="$0.0m" /></label><label>Project description<textarea required name="description" rows={3} placeholder="Summarise the opportunity and delivery plan" /></label><div className="form-actions"><button className="secondary" type="button" onClick={onClose}>Cancel</button><button className="primary" type="submit">Create project →</button></div></form></>}</div></div> }

export default App
